# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-03 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stakeholders', '0001_initial'),
        ('company_accounts', '0001_initial'),
        ('inventory', '0002_auto_20160103_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml_content', models.TextField(blank=True)),
                ('clave_acceso', models.CharField(blank=True, default=b'', max_length=50)),
                ('numero_autorizacion', models.CharField(blank=True, default=b'', max_length=50)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('issues', models.TextField(blank=True, default=b'')),
                ('ambiente_sri', models.CharField(choices=[(b'pruebas', b'Pruebas'), (b'produccion', b'Producci\xc3\xb3n')], max_length=20)),
                ('status', models.CharField(choices=[(b'NotSent', b'No enviado al SRI'), (b'ReadyToSend', b'Enviando al SRI'), (b'Sent', b'Enviada al SRI'), (b'Accepted', b'Aceptada por el SRI'), (b'Annulled', b'Anulado')], default=b'NotSent', max_length=20)),
                ('sri_last_check', models.DateTimeField(blank=True, null=True)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('date', models.DateTimeField()),
                ('secuencial', models.IntegerField(blank=True, default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_accounts.Company')),
                ('issued_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stakeholders.Customer')),
                ('punto_emision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company_accounts.PuntoEmision')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=8, max_digits=20)),
                ('descuento', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Bill')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.SKU')),
            ],
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=8, max_digits=20)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Bill')),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.FormaPago')),
            ],
        ),
        migrations.CreateModel(
            name='PlazoPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('unidad_tiempo', models.CharField(max_length=20)),
                ('tiempo', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='pago',
            name='plazo_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.PlazoPago'),
        ),
    ]
