# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billitem',
            name='descuento',
        ),
        migrations.AddField(
            model_name='billitem',
            name='discount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[(b'NotSent', b'No enviado al SRI'), (b'ReadyToSend', b'Enviando al SRI'), (b'Sent', b'Enviada al SRI'), (b'Accepted', b'Aceptada por el SRI'), (b'Rejected', b'Rechazada por el SRI'), (b'Annulled', b'Anulado')], default=b'NotSent', max_length=20),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='qty',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
