# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-03 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_accounts', '0001_initial'),
        ('sri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_cost', models.DecimalField(decimal_places=8, max_digits=20)),
                ('code', models.IntegerField()),
                ('acquisition_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('distributor_code', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('tipo', models.CharField(choices=[(b'producto', b'Producto (ej. papas, muebles, televisores)'), (b'servicio', b'Servicio (ej. reparaci\xc3\xb3n, transporte, instalaci\xc3\xb3n)')], max_length=10)),
                ('decimales_qty', models.IntegerField(choices=[(0, b'El art\xc3\xadculo se vende por unidades enteras'), (2, b'El art\xc3\xadculo se vende por d\xc3\xa9cimas partes'), (2, b'El art\xc3\xadculo se vende por cent\xc3\xa9simas partes (cent\xc3\xadmetros)'), (3, b'El art\xc3\xadculo se vende por mil\xc3\xa9simas partes (gramos, mil\xc3\xadmetros)')], default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_accounts.Company')),
                ('tax_items', models.ManyToManyField(to='sri.Tax')),
            ],
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=8, max_digits=20)),
                ('unit_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('location', models.CharField(max_length=500)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Batch')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_accounts.Establecimiento')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item'),
        ),
    ]
