# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-03 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchases.Purchase'),
        ),
        migrations.AlterUniqueTogether(
            name='sku',
            unique_together=set([('batch', 'establecimiento')]),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set([('company', 'code')]),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together=set([('item', 'code')]),
        ),
    ]
