# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-06 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20160121_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='qty_unlimited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
