# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-03 19:40
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=6)),
                ('valor_fijo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Ice',
            fields=[
                ('tax_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sri.Tax')),
            ],
            bases=('sri.tax',),
        ),
        migrations.CreateModel(
            name='Iva',
            fields=[
                ('tax_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sri.Tax')),
            ],
            bases=('sri.tax',),
        ),
    ]
