# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-03 19:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stakeholders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('xml_content', models.TextField()),
                ('closed', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('number', models.CharField(max_length=20)),
                ('total', models.DecimalField(decimal_places=8, max_digits=20)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stakeholders.Seller')),
            ],
        ),
    ]
