# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-03 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('qty', models.DecimalField(decimal_places=8, max_digits=20)),
                ('comment', models.TextField(blank=True)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.FormaPago')),
            ],
        ),
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=8, max_digits=20)),
                ('date', models.DateField()),
                ('received', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Bill')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.FormaPago')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='receivable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_receivable.Receivable'),
        ),
    ]
