# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-03 19:40
from __future__ import unicode_literals

import company_accounts.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=100)),
                ('reason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=100)),
                ('ruc', models.CharField(max_length=100)),
                ('razon_social', models.CharField(max_length=100)),
                ('direccion_matriz', models.CharField(max_length=100)),
                ('contribuyente_especial', models.CharField(blank=True, max_length=20)),
                ('obligado_contabilidad', models.BooleanField(default=False)),
                ('siguiente_numero_proforma', models.IntegerField(default=1)),
                ('logo', models.ImageField(blank=True, storage=company_accounts.models.OverwritingStorage(), upload_to=company_accounts.models.logo_path_generator)),
                ('cert', models.CharField(blank=True, max_length=20000)),
                ('key', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_accounts.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=3)),
                ('direccion', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_accounts.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence', models.CharField(choices=[(b'demo', b'Demo'), (b'basic', b'Basic'), (b'professional', b'Professional'), (b'enterprise', b'Enterprise')], default=b'demo', max_length=20)),
                ('expiration', models.DateField(default=datetime.date(2010, 1, 1))),
                ('next_licence', models.CharField(choices=[(b'demo', b'Demo'), (b'basic', b'Basic'), (b'professional', b'Professional'), (b'enterprise', b'Enterprise')], default=b'demo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LicenceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('action', models.TextField()),
                ('licence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_accounts.Licence')),
            ],
            bases=(company_accounts.models.ReadOnlyModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LicenceUpdateRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('action', models.TextField()),
                ('result', models.TextField(blank=True)),
                ('licence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_accounts.Licence')),
            ],
        ),
        migrations.CreateModel(
            name='PuntoEmision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=3)),
                ('siguiente_secuencial_pruebas', models.IntegerField(default=1)),
                ('siguiente_secuencial_produccion', models.IntegerField(default=1)),
                ('ambiente_sri', models.CharField(choices=[(b'pruebas', b'Pruebas'), (b'produccion', b'Producci\xc3\xb3n')], default=b'pruebas', max_length=20)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_accounts.Establecimiento')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='licence',
            field=models.ForeignKey(default=company_accounts.models.default_licence, on_delete=django.db.models.deletion.CASCADE, to='company_accounts.Licence'),
        ),
    ]
