# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 04:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=500)),
                ('fixed', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_accounts.Company')),
            ],
        ),
        migrations.AlterField(
            model_name='bannedcompany',
            name='ruc',
            field=models.CharField(max_length=20),
        ),
    ]
